### ISSUE TITLE
Link not working - BanglaLekha Corpus (Handwriting) (ULAB, Dhaka)

### ISSUE THREAD

**Issue by shahedex** [banglakit/awesome-bangla#7]
The attached link of "BanglaLekha Corpus (Handwriting) (ULAB, Dhaka)" in the "Corpora (Corpus) and Datasets" section is not working. 
BTW, I've found the dataset on [BanglaLekha-Isolated](https://data.mendeley.com/datasets/hf6sf8zrkc/2)

**Comment by aniruddha-adhikary** [comment]
Thank you @shahedex  :+1:
